### PR TITLE
COP-603: Update send-notifications to send-notification

### PR DESCRIPTION
**Pull request by joshuadiablito**

### CODE REVIEW

**Comment by aminmc** [comment]
I'm not sure why you are looking to change the bpmn file name from notifications to notification. The BPMN supports sending multiple emails and/or text messages. Sorry but not approving this PR.

**Comment by joshuadiablito** [comment]
Okay, I was changing it to keep it in line with the ID of the BPMN - so should the ID of the BPMN be changed to send-notifications?

**Comment by aminmc** [comment]
@joshuadiablito @pixie79 I have updated the ID and corresponding test cases.  Please update your BPMNs to use 'send-notifications'. The corresponding documentation have also been updated.

**Comment by joshuadiablito** [comment]
Amazing work, thanks Amin! :)

**Pull request closed without merging**
